version: '3.8'

services:
  backend:
    image: backend:latest
    ports:
      - "8080:8080"

  frontend:
    image: frontend:latest
    ports:
      - "5001:5001"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
