version: '3.8'

services:
  backend:
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    image: frontend:latest
    ports:
      - "5001:5001"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"